name: feedforward_env
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.21
  - matplotlib=3.7.1
  - jupyter=1.0.0
  - pip  # Ensure pip is included
  - pip:
      - jupyter  # Install jupyter via pip as a backup
