name: ffn
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # Use CUDA Toolkit version 11.8, which is supported
  - numpy=1.21
  - matplotlib=3.7.1
  - jupyter
