name: ffn
channels:
  - nvidia
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.21
  - matplotlib=3.7.1
  - jupyter=1.0.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio
  - cudatoolkit=11.8
  - scikit-learn=0.24.2
